"""Build published/queue.md — the upcoming posting plan — from post headers.

Usage: python3 scripts/build_queue.py [START_DATE=YYYY-MM-DD]

- Reads every post in generated/drafts/<pillar>/ and its STATUS: line.
- Posts with STATUS: published are skipped; draft, approved and scheduled are queued.
- Starts on the Monday of the given date, default the next Monday from today
  (today, if today is Monday).
- One post per pillar per week, seven days a week. When a pillar has
  nothing left, its slot is marked "write next" so the gap is visible.

Only published/queue.md is written. published/linkedin.md is the hand-kept
published log and is never touched by this script.
"""
import datetime, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRAFTS = os.path.join(ROOT, "generated", "drafts")
QUEUE = os.path.join(ROOT, "published", "queue.md")
# weekday (Mon=0) -> pillar folder, or a pair that alternates week by week
SCHEDULE = {0: "dsa", 1: "ai-engineering", 2: "software-engineering",
            3: "system-architecture", 4: "business", 5: "building", 6: "dev-growth"}
QUEUED = {"draft", "approved", "scheduled"}
# pillar folder -> series label, so empty slots read like filled ones
LABELS = {"dsa": "DSA SERIES", "software-engineering": "SOFTWARE ENGINEERING",
          "system-architecture": "SYSTEM ARCHITECTURE", "ai-engineering": "AI ENGINEERING",
          "dev-growth": "DEV GROWTH", "building": "BUILDING",
          "business": "FOR BUSINESS / SOLUTIONS"}
ROADMAPS = {"dsa": "01-dsa-problem-solving.md", "software-engineering": "02-software-engineering.md",
            "system-architecture": "03-system-design.md", "ai-engineering": "04-ai-engineering.md",
            "dev-growth": "05-dev-growth.md",
            # no roadmap: BUILDING from sources/project-log.md, FOR BUSINESS from
            # sources/apps.md (PRODUCT) or a system idea (BLUEPRINT)
            "building": None, "business": None}


def roadmap(pillar):
    """{n: 'Title · MODE'} from the pillar's roadmap lines ({} for story pillars)."""
    if ROADMAPS[pillar] is None:
        return {}
    text = open(os.path.join(ROOT, "pillars", ROADMAPS[pillar])).read()
    return {int(n): f"{t} · {m}" for n, t, m in re.findall(r"^- #(\d+) (.+?) · ([A-Z]+) · needs", text, re.M)}


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else None


def num(path):
    return int(re.search(r"-(\d+)-", os.path.basename(path)).group(1))


def main():
    if len(sys.argv) > 1:
        start = datetime.date.fromisoformat(sys.argv[1])
        start -= datetime.timedelta(days=start.weekday())
    else:
        today = datetime.date.today()
        start = today + datetime.timedelta(days=(7 - today.weekday()) % 7)

    queue, skipped, upcoming = {}, 0, {}
    pillars = {p for v in SCHEDULE.values() for p in (v if isinstance(v, tuple) else (v,))}
    for pillar in pillars:
        posts = []
        files = sorted(glob.glob(os.path.join(DRAFTS, pillar, "*.md")), key=num)
        last = num(files[-1]) if files else 0
        road = roadmap(pillar)
        upcoming[pillar] = [f"#{n:02d} {road[n]}" for n in sorted(road) if n > last]
        if ROADMAPS[pillar] is None:
            upcoming[pillar] = None  # never runs out: always "write from the project log"
        for f in files:
            text = open(f).read()
            status = (field(text, "STATUS") or "draft").lower()
            if status not in QUEUED:
                skipped += 1
                continue
            posts.append((f, text, status))
        queue[pillar] = posts

    out = ["# Posting Queue", "",
           "Generated by `python3 scripts/build_queue.py` — do not edit by hand.",
           "Change a post's STATUS: line instead, then re-run the script.",
           "The record of what went live is `published/linkedin.md`.", "",
           "Schedule: Mon DSA · Tue AI Engineering · Wed Software Engineering · Thu System Architecture · Fri For Business · Sat Building · Sun Dev Growth",
           "Before posting: fill or delete any [PERSONAL: ...] line. 🖼 posts need an image made from HEADLINE + LAYOUT; 🎞 posts need one slide per SLIDES line (PDF for LinkedIn, images for Instagram); ✍ posts go out as text only."]
    day, week = start, 0
    while any(queue.values()):  # after the last draft, open slots name the next roadmap post
        if day.weekday() == 0:
            week += 1
            out += ["", f"## Week {week} — from {day:%a %d %b %Y}", "",
                    "| Date | Series | Title | Mode | Format | Status | File |", "| --- | --- | --- | --- | --- | --- | --- |"]
        pillar = SCHEDULE.get(day.weekday())
        if isinstance(pillar, tuple):
            pillar = pillar[(week - 1) % 2]
        if pillar:
            if queue[pillar]:
                f, text, status = queue[pillar].pop(0)
                mark = " ✎" if "[PERSONAL" in text else ""
                rel = os.path.relpath(f, os.path.dirname(QUEUE))
                fmt = "🖼 visual" if field(text, "FORMAT") == "VISUAL" else "✍ text"
                if field(text, "LAYOUT") == "CAROUSEL":
                    n = len(re.findall(r"^\s+\d{2} · ", text.split("\n---\n")[0], re.M)) + 1
                    fmt = f"🎞 carousel ({n} slides)"
                out.append(f"| {day:%a %d %b} | {field(text, 'SERIES')} | {field(text, 'TITLE')}{mark} "
                           f"| {field(text, 'MODE')} | {fmt} | {status} | [{os.path.basename(f)}]({rel}) |")
            else:
                if upcoming[pillar] is None:
                    nxt = ("a PRODUCT (sources/apps.md) or a BLUEPRINT post" if pillar == "business"
                           else "next post from sources/project-log.md")
                else:
                    nxt = upcoming[pillar].pop(0) if upcoming[pillar] else "roadmap finished"
                out.append(f"| {day:%a %d %b} | {LABELS[pillar]} | — write: {nxt} — | | | | |")
        day += datetime.timedelta(days=1)

    out += ["", "✎ = has a [PERSONAL: ...] line to fill in or delete."]
    open(QUEUE, "w").write("\n".join(out) + "\n")
    print(f"{week} weeks written to published/queue.md ({skipped} published posts skipped)")


if __name__ == "__main__":
    main()
