"""Build published/queue.md — the upcoming posting plan — from post headers.

Usage: python3 scripts/build_queue.py [START_DATE=YYYY-MM-DD]

- Reads every post in generated/drafts/<pillar>/ and its STATUS: line.
- Posts with STATUS: published are skipped; draft, approved and scheduled are queued.
- Starts on the Monday of the given date, default the next Monday from today
  (today, if today is Monday).
- One post per pillar per week. When a pillar has nothing left, its slot is
  marked "write next" so the gap is visible.

Only published/queue.md is written. published/linkedin.md is the hand-kept
published log and is never touched by this script.
"""
import datetime, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRAFTS = os.path.join(ROOT, "generated", "drafts")
QUEUE = os.path.join(ROOT, "published", "queue.md")
# weekday (Mon=0) -> pillar folder
SCHEDULE = {0: "dsa", 1: "ai-engineering", 2: "software-engineering",
            3: "system-architecture", 6: "dev-growth"}
QUEUED = {"draft", "approved", "scheduled"}


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else None


def num(path):
    return int(re.search(r"-(\d+)-", os.path.basename(path)).group(1))


def main():
    if len(sys.argv) > 1:
        start = datetime.date.fromisoformat(sys.argv[1])
        start -= datetime.timedelta(days=start.weekday())
    else:
        today = datetime.date.today()
        start = today + datetime.timedelta(days=(7 - today.weekday()) % 7)

    queue, skipped = {}, 0
    for pillar in set(SCHEDULE.values()):
        posts = []
        for f in sorted(glob.glob(os.path.join(DRAFTS, pillar, "*.md")), key=num):
            text = open(f).read()
            status = (field(text, "STATUS") or "draft").lower()
            if status not in QUEUED:
                skipped += 1
                continue
            posts.append((f, text, status))
        queue[pillar] = posts

    out = ["# Posting Queue", "",
           "Generated by `python3 scripts/build_queue.py` — do not edit by hand.",
           "Change a post's STATUS: line instead, then re-run the script.",
           "The record of what went live is `published/linkedin.md`.", "",
           "Schedule: Mon DSA · Tue AI Engineering · Wed Software Engineering · Thu System Architecture · Sun Dev Growth",
           "Before posting: fill or delete any [PERSONAL: ...] line, then make the image from HEADLINE + LAYOUT."]
    day, week = start, 0
    while any(queue.values()):
        if day.weekday() == 0:
            week += 1
            out += ["", f"## Week {week} — from {day:%a %d %b %Y}", "",
                    "| Date | Series | Title | Status | File |", "| --- | --- | --- | --- | --- |"]
        pillar = SCHEDULE.get(day.weekday())
        if pillar:
            if queue[pillar]:
                f, text, status = queue[pillar].pop(0)
                mark = " ✎" if "[PERSONAL" in text else ""
                rel = os.path.relpath(f, os.path.dirname(QUEUE))
                out.append(f"| {day:%a %d %b} | {field(text, 'SERIES')} | {field(text, 'TITLE')}{mark} "
                           f"| {status} | [{os.path.basename(f)}]({rel}) |")
            else:
                out.append(f"| {day:%a %d %b} | {pillar} | — write next post — | | |")
        day += datetime.timedelta(days=1)

    out += ["", "✎ = has a [PERSONAL: ...] line to fill in or delete."]
    open(QUEUE, "w").write("\n".join(out) + "\n")
    print(f"{week} weeks written to published/queue.md ({skipped} published posts skipped)")


if __name__ == "__main__":
    main()
