"""Show which posts work: published/linkedin.md numbers, grouped by post traits.

Usage: python3 scripts/report.py

Reads the metric columns in published/linkedin.md, joins each row to its draft
by the SERIES line, and writes published/report.md: engagement grouped by
pillar, mode, format (text / image / carousel), type, body length and posting
day. Rows without impressions yet are skipped.

Engagement rate = (reactions + comments + reposts + saves) / impressions.
Small groups mislead: treat anything under 5 posts as a hint, not a result.
"""
import datetime, glob, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.join(ROOT, "published", "linkedin.md")
REPORT = os.path.join(ROOT, "published", "report.md")
METRICS = ["Impressions", "Reactions", "Comments", "Reposts", "Saves", "Followers"]
MIN_GROUP = 5   # below this, a group is a hint
MARKER_LINE = re.compile(r"^\[(PERSONAL|FACT_CHECK):.*\]\s*$", re.M)
LENGTHS = [(1500, "under 1,500"), (2000, "1,500–2,000"), (2500, "2,000–2,500"), (10**9, "over 2,500")]


def length_band(text):
    """Characters actually posted: the body without marker lines."""
    body = text.split("\n---\n", 1)[1] if "\n---\n" in text else ""
    n = len(MARKER_LINE.sub("", body).strip())
    return next(label for limit, label in LENGTHS if n < limit)


def weekday(date):
    try:
        return datetime.date.fromisoformat(date).strftime("%a")
    except ValueError:
        return "—"


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else None


def drafts_by_series():
    out = {}
    for f in glob.glob(os.path.join(ROOT, "generated", "*", "*", "*.md")):
        text = open(f).read()
        series = field(text, "SERIES")
        if series:
            layout = field(text, "LAYOUT")
            if layout == "CAROUSEL":
                kind = "carousel"
            elif field(text, "FORMAT") == "TEXT":
                kind = "text"
            else:
                kind = "image"
            out[series] = {"pillar": os.path.basename(os.path.dirname(f)), "mode": field(text, "MODE") or "—",
                           "format": kind, "type": field(text, "TYPE") or "—",
                           "length": length_band(text)}
    return out


def read_log():
    rows, header = [], None
    for line in open(LOG).read().splitlines():
        if not line.startswith("|") or line.startswith("| ---"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if header is None:
            header = cells
            continue
        rows.append(dict(zip(header, cells)))
    return rows


def number(v):
    v = v.replace(",", "").strip()
    return int(v) if v.isdigit() else None


def table(title, groups):
    lines = [f"## By {title}", "", "| Group | Posts | Avg impressions | Engagement rate | Followers gained |",
             "| --- | --- | --- | --- | --- |"]
    for key, posts in sorted(groups.items(), key=lambda kv: -rate(kv[1])):
        hint = "" if len(posts) >= MIN_GROUP else " (hint)"
        imp = sum(p["Impressions"] for p in posts)
        lines.append(f"| {key}{hint} | {len(posts)} | {imp // len(posts):,} | {rate(posts):.1%} "
                     f"| {sum(p['Followers'] or 0 for p in posts)} |")
    return lines + [""]


def rate(posts):
    imp = sum(p["Impressions"] for p in posts)
    eng = sum((p["Reactions"] or 0) + (p["Comments"] or 0) + (p["Reposts"] or 0) + (p["Saves"] or 0) for p in posts)
    return eng / imp if imp else 0


def main():
    drafts = drafts_by_series()
    posts, unmatched = [], []
    for row in read_log():
        nums = {m: number(row.get(m, "")) for m in METRICS}
        if not nums["Impressions"]:
            continue
        d = drafts.get(row.get("Series", ""))
        if not d:
            unmatched.append(row.get("Series", "?"))
            continue
        posts.append({**d, **nums, "series": row["Series"], "title": row.get("Title", ""),
                      "day": weekday(row.get("Date", ""))})

    out = ["# Content Report", "", "Generated by `python3 scripts/report.py` — do not edit by hand.", ""]
    if not posts:
        out.append("No posts with numbers yet. Fill the metric columns in `published/linkedin.md` "
                   "seven days after each post goes live.")
    else:
        out += [f"{len(posts)} posts with numbers. Groups under {MIN_GROUP} posts are marked (hint).", ""]
        for key, title in [("pillar", "pillar"), ("mode", "mode"), ("format", "format"), ("type", "type"),
                           ("length", "body length (characters)"), ("day", "posting day")]:
            groups = {}
            for p in posts:
                groups.setdefault(p[key], []).append(p)
            if list(groups) != ["—"]:   # skip a trait no post has yet
                out += table(title, groups)
        top = sorted(posts, key=lambda p: -rate([p]))[:5]
        out += ["## Top 5 posts by engagement rate", ""]
        out += [f"{i}. {p['series']} — {p['title']} ({rate([p]):.1%}, {p['Impressions']:,} impressions)"
                for i, p in enumerate(top, 1)]
    if unmatched:
        out += ["", "Rows whose Series matches no draft (fix the Series cell): " + ", ".join(unmatched)]
    open(REPORT, "w").write("\n".join(out) + "\n")
    print(f"published/report.md written ({len(posts)} posts with numbers, {len(unmatched)} unmatched)")


if __name__ == "__main__":
    main()
